import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { MantineProvider } from "@mantine/core";
import '@mantine/core/styles.css';
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster
          position="top-center"
          reverseOrder={false}
        />
        <MantineProvider forceColorScheme="light">
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
