import { Inter } from "next/font/google";
import "../globals.css";
import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';
import { Toaster } from "react-hot-toast";
import Sidebar from "@/components/Sidebar";
import Layout from "@/components/Layout";
import NextTopLoader from 'nextjs-toploader';
import ContextProvider from "@/context/ContextProvider";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader color="#6366f1" />
        <ContextProvider>
          <Layout>
            <Toaster
              position="top-center"
              reverseOrder={false}
            />
            <main className="bg-light min-h-[100vh] flex md:flex-row flex-col w-full relative">
              <Sidebar />
              <section className="flex-1 max-w-full overflow-hidden container">
                {children}
              </section>
            </main>
          </Layout>
        </ContextProvider>
      </body>
    </html>
  );
}
